### ISSUE TITLE
The variable ... is not in scope.

### ISSUE THREAD

**Issue by Osmosis311** [wvbe/node-schematron#21]
Hi!

I'm currently working on a project for a volunteer ambulance service, and we need to validate against the NEMSIS national [schematron](https://nemsis.org/technical-resources/version-3/version-3-schematron/) (attached), and I'm getting this error `The variable nemSch_lookup_elements is not in scope`

Is there any chance this library is able to "handle" this file?

I see there was a [similar](https://github.com/gap777/SchemaTron/issues/9) issue raised in a .NET schematron validation library, and the response from the author of that library is that NEMSIS is using an XML spec that hasn't been released yet (but that answer is from 2015).

Any advice you can provide would be greatly appreciated!

[national.txt](https://github.com/wvbe/node-schematron/files/9492830/national.txt)

Thanks!

**Comment by wvbe** [comment]
Hey @Osmosis311, thanks for including all of that information in your ticket!

Currently, this library does not handle any processing instruction (`<?DSDL_INCLUDE_START`), nor does it handle `<sch:include>`. I've focussed on what's described in [the ISO/IEC 19757-3 PDF](https://github.com/wvbe/node-schematron/blob/master/docs/c055982_ISO_IEC_19757-3_2016.pdf) -- but from that PDF's I had to put `<sch:include>` out of scope for a reason I don't remember.

I'm not exactly sure how DSDL inclusion PI's are supposed to work -- From what I gathered about DSDL inclusion PI's is that it is like a DITA conref (and very similar to `<sch:include>`, basically just supplanting content from one file to another. I imagine that you might be able to use an XML transformation (eg. using XSLT) to supplant this content even before the updated schematron is fed back into `node-schematron`. That would at least solve the compatibility issue with `<?DSDL_INCLUDE_START`. However, in `national.txt` I am also not sure what the intent of the `<sch:variable>` _child elements_ are: `<nemSch_lookup_elements>` and others (presumably everything in the null namespace is a NEMSIS element?).

You are of course welcome to fork/redistribute this library as you wish, it is MIT licensed. However, I cannot support NEMSIS elements in my copy of `node-schematron`. Although `<?DSDL_INCLUDE_START` would not be unfathomable for `node-schematron` I would then rather implement `<sch:include>` first -- and that is only useful to you if you can transform your Schematron in the first place :)

I think your best bet is to transform the schematron file before feeding it into a schema processor. I suspect you will run into trouble handling NEMSIS elements too -- for which I have no solution other than to add more logic to your Schematron processor of choice. Sorry!

**Comment by Osmosis311** [comment]
Understood.  Thank you very much for the guidance and the potential solutions!  Much appreciated!
