### ISSUE TITLE
Slimdom error

### ISSUE THREAD

**Issue by AmirSarvestani** [wvbe/node-schematron#9]
I've been trying to use the library but I get this weird namespace error with slimdom when trying to compile the whole library. Is there a problem here? Can you please look into it?

And other thing is that you need to add the .babelrc.js file to the zipped repo so the tests will pass :) 

Thanks

**Comment by AmirSarvestani** [comment]
Seems the issue was with using yarn instead of npm! It seems good. Sorry!

**Comment by wvbe** [comment]
Thanks for posting back @AmirSarvestani! Also, my apologies for not having noticed your issue sooner. Glad it worked out 👍
